<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AiProviderBenchmarker.Application\AiProviderBenchmarker.Application.csproj" />
    <ProjectReference Include="..\AiProviderBenchmarker.Infrastructure\AiProviderBenchmarker.Infrastructure.csproj" />
    <ProjectReference Include="..\AiProviderBenchmarker.Domain\AiProviderBenchmarker.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>b27cf74d-8d0f-4283-9c37-3d06a0311172</UserSecretsId>
  </PropertyGroup>

</Project>
